apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskprocessor
spec:
  selector:
    matchLabels:
      app: taskprocessor
  template:
    metadata:
      labels:
        app: taskprocessor
    spec:
      containers:
      - name: taskprocessor
        image: den86/taskprocessorapi
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: taskprocessor
spec:
  type: NodePort
  selector:
    app: taskprocessor
  ports:
  - port: 80
    targetPort: 3000
    nodePort: 32222
  
